version: "3"
services:
  postgres:
    image: postgres
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=controleAcoes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres