version: "3"
services:
  # Postgres
  postgres:
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=controleAcoes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres-compose-network
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "adrianomrodrigues@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

  #Localstack - mock for aws services
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "12345:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack
#      - HOSTNAME_EXTERNAL=192.168.99.101
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
networks:
  postgres-compose-network:
    driver: bridge